### ISSUE TITLE
CloudLaunch v0.2  privacy error, the website is permanently loading

### ISSUE THREAD

**Issue by HEHgit** [galaxyproject/cloudlaunch#132]
Hi,

I'm using CloudLaunch for galaxy cloudman.
CloudLaunch was working until yesterday, but today I can't open the website because of a privacy error:
NET::ERR_CERT_COMMON_NAME_INVALID.
I'm using Chrome but I also tried with Explorer, Firefox and in the incognito mode, and I got the same issue all the time. I can bypass the privacy error in Fifefox, but then the website  is permanently loading without opening. 

Thank you in advance for your help.

**Comment by nuwang** [comment]
@HEHgit I couldn't recreate the issue locally in incognito as well as after updating to the latest chrome (63.0.3239.132) - could it be that your clock is out of sync as suggested here? https://www.drivereasy.com/knowledge/fix-err-cert-common-name-invalid-chrome-solved/

**Comment by HEHgit** [comment]
@nuwang Thanks for your answer, actually the data and time are correct in my device

**Comment by nuwang** [comment]
@HEHgit Thanks for the info - I think we've identified the issue. We've switched over to launch.usegalaxy.org from beta.launch.usegalaxy.org. Using the old name results in this error. We'll see whether we can fix this so that old clients are transparently redirected. Thanks for reporting this and please let us know whether the problem goes away when using the new dns name.

**Comment by HEHgit** [comment]
Thank you so much!

**Comment by nuwang** [comment]
This has been fixed in: https://github.com/galaxyproject/ansible-cloudlaunch/commit/20232224e808a321e84c7af810fd187066692732 and now beta.launch.usegalaxy.org will redirect to launch.usegalaxy.org. Thanks again for reporting @HEHgit .
