### ISSUE TITLE
Performing GET on api-auth-token endpoint results in internal server error

### ISSUE THREAD

**Issue by nuwang** [galaxyproject/cloudlaunch#145]
I visited https://launch.usegalaxy.org/cloudlaunch/api/v1/auth/api-token-auth/, following the instructions in https://github.com/CloudVE/cloudlaunch-cli -> step 4.

It resulted in an internal server error.

Once I manually created the token from within the cloudlaunch admin, it returned the token correctly. So it looks like GET doesn't behave properly if no token is defined.

@machristie Did you experience this too?

**Comment by machristie** [comment]
I think maybe I was thinking that api-token-auth would get_or_create the token, but we changed it to just get the token. 

An [API token is created when a user is created](https://github.com/galaxyproject/cloudlaunch/blob/dev/django-cloudlaunch/cloudlaunch/models.py#L21), but we need a way to create tokens for existing users.  Would a Django migration be the best way to do that?

**Comment by machristie** [comment]
This was fixed by @nuwang in [a commit where GET handles missing token and POST can be used to create a token](https://github.com/galaxyproject/cloudlaunch/commit/691a2b6e7c78c6e3adcb67aab4e97fff44737815).

This issue can be closed now. However, I will also open an issue in cloudlaunch-cli to make sure that this gets documented how to get an API token.
