### ISSUE TITLE
Invalid name: cloudlaunch_key_pair

### ISSUE THREAD

**Issue by meokchen** [galaxyproject/cloudlaunch#154]
How can I figure this Error as below:
FAILURE 
Create appliance task failed: Invalid name: cloudlaunch_key_pair. Name must be at least 3 characters long and at most 63 characters. It must consist of lowercase letters, numbers, or dashes. The name must not start or end with a dash.

Thanks so much!

**Comment by nuwang** [comment]
@meokchen Can you let us know which application you were trying to launch when this error came up? The issue seems to be with the name of the key pair, which, due to a recent change, should have dashes instead of underscores. It could be a misconfiguration of our backend after the upgrade a few days ago.
