### ISSUE TITLE
Cannot terminate appliance

### ISSUE THREAD

**Issue by keenanw27** [galaxyproject/cloudlaunch#189]
Hello, I am unable to terminate and appliance. I get the following message:

UNABLE TO CHECK STATUS
Delete task failed: CloudBridgeBaseException: Unable to locate credentials from exception type: <class 'botocore.exceptions.NoCredentialsError'>

I didn't realize this instance hadn't been terminated and incurred substantial unintended costs. Please let me know how to make sure this is terminated.

**Comment by almahmoud** [comment]
Hello,
Thank you for raising this issue.

It is advised to always check in the cloud console itself after you are done using an appliance. We try to have the most robust cleanup possible across clouds. As such, if there are issues we would gladly try to fix specific problems and generally take suggestions to improve the cleanup process. However, we unfortunately cannot guarantee that the cleanup will always be 100% reliable. Leftover resources can happen due to permission issues, race conditions, missing/expired credentials, or a number of other problems. Regarding your specific exception: the cleanup process is relying on your credentials being saved in your user profile, remaining valid, and having the appropriate permissions to delete those resources. It seems your credentials cannot be found when attempting to retrieve the state of your instance. If your credentials have changed or are not saved, you will not be able to manage appliances in CloudLaunch.
Furthermore, if you do not wish to keep any data from your deployment (i.e. the persistent volumes for the shared filesystem and the databases), you must delete them in the console. If you are having trouble finding or deleting any resources, let us know what cloud you are using and we will assist to the best of our ability.
