### ISSUE TITLE
Cloudman

### ISSUE THREAD

**Issue by capraemanuele** [galaxyproject/cloudlaunch#195]
UNABLE TO CHECK STATUS
Delete task failed: CloudBridgeBaseException: Unable to locate credentials from exception type: <class 'botocore.exceptions.NoCredentialsError'>

**Comment by almahmoud** [comment]
This is likely due to credentials not being saved in CloudLaunch. If you opt not to save your credentials in your profile, CloudLaunch will be unable to monitor the instance. If you have the credentials saved but this is still showing up, could you please provide some information on what appliance you are launching, and for how long has it been running? I'll be happy to look into it and see if there is any bug on our end.

**Comment by capraemanuele** [comment]
I type the corrected credential and now the galaxy cloud work hovever in cloud launch the error message still remain:


is this a problem? Can I continue to use galaxy cloud without problem?
Thank you in advance
Emanuele

    Il giovedì 23 aprile 2020, 11:15:48 CEST, Alexandru Mahmoud <notifications@github.com> ha scritto:  
 
 


This is likely due to credentials not being saved in CloudLaunch. If you opt not to save your credentials in your profile, CloudLaunch will be unable to monitor the instance. If you have the credentials saved but this is still showing up, could you please provide some information on what appliance you are launching, and for how long has it been running? I'll be happy to look into it and see if there is any bug on our end.

**Comment by almahmoud** [comment]
As previously mentioned, the error is expected if you do not save your credentials before the launch because CloudLaunch does not keep your credentials so it cannot check on the status of the machine. It does not affect your live instance, you just have to make sure to clean up resources manually when you're done with it as CloudLaunch does not have your credentials after the launch to do so for you.
