### ISSUE TITLE
Galaxy on Nectar cloud

### ISSUE THREAD

**Issue by Mrudhulaks** [galaxyproject/cloudlaunch#201]
Hi,

I am trying to launch galaxy on nectar cloud using GVL server.

I followed the tutorial to launch https://melbournebioinformatics.github.io/MelBioInf_docs/tutorials/gvl_launch/gvl_launch/

However, I could not launch it. I got the following error

mrudhula-genomics-virtual-lab-20-06-16t06-48Appliance: Genomics Virtual Lab (GVL) Version: GVL 5.0 beta2 (Galaxy 20.01) Cloud: NeCTAR | 3 minutes ago | FAILURE Create appliance task failed: CloudBridgeBaseException: The requested availability zone is not available (HTTP 400) (Request-ID: req-064820e3-cb95-4353-8200-dc61c7e68148) from exception type: <class 'novaclient.exceptions.BadRequest'>  Report this failure?
-- | -- | --

Could you please help me with this.

Thank you.

Regards,
MK

**Comment by nuwang** [comment]
@Mrudhulaks According to the error message, it looks like there are not enough nodes in the availability zone you selected. It can be a bit tricky to get resources because NeCTAR is often running at capacity. Try selecting the "Default" zone in the launch page.

![image](https://user-images.githubusercontent.com/2070605/84752729-c2419d00-afdb-11ea-884f-2eacc84f2571.png)

This will try to use any zone that's available.

**Comment by Mrudhulaks** [comment]
Thank you for the prompt response. I tried all available zones on Nectar Melbourne. I got the same error. I tried using "Default" zone as well. I could not go beyond "Retrieving instance type" and launch it on "Default"

**Comment by nuwang** [comment]
@Mrudhulaks It's most likely a transient capacity problem. It may be worth trying to launch again when a sufficient period of time has elapsed, and in non-peak hours so there's a higher chance of being able to get a VM. Let us know how it goes.
