### ISSUE TITLE
Access denied for GVL launch using AWS

### ISSUE THREAD

**Issue by vijayjidigam** [galaxyproject/cloudlaunch#207]
HI,

I'm trying launch GVL it shows me following error. I was already using cloud man but most of my Tools on Galaxy doesn't work. I was told by some one that Gal is updated version. SO i am trying to launch GVL with different log in credentials and different was account. Please help me in fixing this problem.

FAILURE 
Create appliance task failed: An error occurred (AccessDenied) when calling the GetRole operation: User: arn:aws:iam::387991834029:user/GVLcloud is not authorized to perform: iam:GetRole on resource: role kumargvlcloud-cm2-kube-role.

Thank you
Vijay

**Comment by afgane** [comment]
This is because your AWS IAM account does not have sufficient privileges. See this issue for details on how to setup proper IAM policies: https://github.com/galaxyproject/cloudlaunch/issues/198#issuecomment-655128278

**Comment by vijayjidigam** [comment]
Hi,

Thank you for your reply. I was able to give administrator access for the newly created IAM user. I went a few steps ahead and was able to see the access address with the following error. Your help is appreciated.

UNABLE TO CHECK STATUS
Health check failed: CloudBridgeBaseException: Unable to locate credentials from exception type: <class 'botocore.exceptions.NoCredentialsError'>

Thank you
Vijay

**Comment by afgane** [comment]
This is not necessarily an error and it occurs because you did no save your AWS credentials in your profile on CloudLaunch. As a result, CloudLaunch cannot check on the status of the machine it launched although the machine may be running just fine. If you choose to save your credentials, future launches will not report this message. 

Also, it will be necessary to log into the AWS console and delete the machine and disks that were created during the initial launch.
