### ISSUE TITLE
EBS optimization is not enabled when selected

### ISSUE THREAD

**Issue by hackdna** [galaxyproject/cloudlaunch#57]
Running commit afbae38a7 in a private Cloud Launch instance. Starting a cluster with a c4.large master and _EBS-optimized_ setting enabled under advanced options. However, `ec2 describe-instances` reports `"EbsOptimized": false` for that instance. There are no errors in the `tasks.log` except for the one described in #56.

**Comment by afgane** [comment]
This is most likely due to the BioBlend version - the latest code has not been published to pypy yet. So can you run the following command (inside the virtual env used by CloudLaundh), restart CloudLaunch and see if that fixes this and #56?

`pip install -U git+https://github.com/galaxyproject/bioblend.git`

**Comment by hackdna** [comment]
Thanks, it fixed this problem. However, I still see the 400 error from #56.
